#!/usr/bin/env bash
# transfers the file from our client to server
num_of_parameter=$#
if [[ $num_of_parameter -lt 3 ]]
then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
	scp -i "$4" "$1" "$3"@"$2":~/
fi
