#!/usr/bin/env bash
# permanent 302 redirection https://github.com/solomon1227;
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://github.com/solomon1227;
    }
}" >> /etc/nginx/sites-available/default
service nginx restart
