#!/usr/bin/env bash
# Install aand configure nginx web server

apt-get update
apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://github.com/solomon1227;
    }
}" >> /etc/nginx/sites-available/default
service nginx restart
