#!/usr/bin/env bash
# Update package lists and install Nginx
apt-get update
apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.html

# Create a custom 404 error page
sudo mkdir -p /var/www/html/errors
echo "<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <p>Ceci n'est pas une page</p>
</body>
</html>" | tee /var/www/html/errors/404.html

# Configure Nginx to use the custom 404 page

echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index index.nginx-debian.html;
    
    add_header X-Served-By \$hostname;
    
    location /redirect_me {
        return 301 https://github.com/solomonferede1;
        }

    error_page 404 /errors/404.html;
    location  /errors/404.html {
        internal;
        }
}" > /etc/nginx/sites-available/default
# Test and reload Nginx
service nginx restart
