#!/usr/bin/env bash
# Install and configure nginx web server

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index index.html index.htm index.nginx-debian.html;
    
    add_header X-Served-By \$hostname;

    location /redirect_me {
        return 301 https://github.com/solomonferede1;
    }
    error_page 404 /404.html;
    location = /404.html{
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
