#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
apt-get update
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.7
apt-get install -y haproxy=2.7.\*
echo "
frontend http
    bind *:80
    default_backend web-back

backend web_back
    balance roundrobin
    server web-01 3.84.222.93:80 check
    server web-02 100.25.139.107:80 check " >> ~/etc/haproxy/haproxy.cfg
service haproxy restart