#!/usr/bin/env bash
# Installing and configuring haproxy load balancer
# Update the system
sudo apt update
sudo apt upgrade -y

# Install HAProxy
sudo apt install -y haproxy

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo chown  "$USER":"$USER" /etc/haproxy/haproxy.cfg
echo "
frontend web_frontend
    bind *:80
    mode http
    default_backend web_backend

backend web_backend
    mode http
    balance roundrobin
    server web-01 54.237.25.186:80 check
    server web-02 100.25.21.22:80 check" >> /etc/haproxy/haproxy.cfg
# Start HAProxy service
sudo service haproxy restart
