#!/usr/bin/env bash
# Write a Bash script that generates a MySQL dump and creates a compressed archive out of it.
today=$(date +"%d-%m-%Y")
mysqldump -u root -p"$1" --all-databases > backup.sql
tar -czvf "$today".tar.gz backup.sql
