#!/usr/bin/env bash
# try to correct nginx not listnen to port 80
sudo apt-get install nginx
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx start
kill "$(pgrep 'nginx' | head -1)"