#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration, 
# displays Best School and then Hi on a new line.
i=1
while [ "$i" -lt 21 ]
do
    case $i in

    4)
        echo $i
        echo "bad luck from China"
        ;;
    9)
        echo $i
        echo "bad luck from japan"
        ;;
    17)
        echo $i
        echo "bad luck from Italy"
        ;;
    *)
        echo $i
        ;;
    esac
    ((i++))
done