#!/usr/bin/env bash
# display hour and minute
hour=0
minute=1
while [ $hour -le 12 ]
do
    echo "Hour: $hour"

    while [ $minute -lt 60 ]
    do
        echo $minute
        ((minute++))
    done
    minute=1

    ((hour++))
done