#!/usr/bin/env bash
# Bash script that configures a Ubuntu server to resolve localhost to 127.0.0.2 and facebook.com to 8.8.8.8.
cp -f /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed 's/157.240.11.35/8.8.8.8    facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
